language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ppsosqq@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.9 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.117.110
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: PMC7OF9yFtogEYcDfydkODMmrR68LzLoyfw8nfWzoiNNzzYocngRw69pGzJUTV6KSAdaut3ylmqVfSvBiPY6UQQNHFlGtEA7mvmXU+mgjICruvUZjUBhKNJgn3NErGRL8ROY2yyxSuvxt4F5r7xJHTHPHG9Yl7WU3RTRLKXoYoJdMKeEAbaiimg8MxEZVShQ1Tou3+JQYghTT1FVNbegyklVWDcBQ75mGN7mXfEIdZiERrufMXmMluGkklyEOqY1Fv7hHZ48SURf1k0eo8YYKfnp5qWXHUNFj8bhxF8ObO7EOgNiCcQ7BEvvfZYRczzsSyA1HGtVhDl4YHhP0cez39ebU3huW5oqE1gCPNL0QBUM9IPB2kgA6UWwD7QOa2bQCrkYWcqMeFP7CaWWYG4AeNjDaEDf0XYwHjFozEhPg0iwrIJB+0bD+8Sl7ub4Jr5f4MDp8eBpTmY5jXLQaZa/6ANJeQdyayi9zXyldhJV8Nb00oO1FvXeEB7drCUxq+elXBUuO6zs1ova61l2SztrueSoNIabp7YIVvOiAEkouGRcDcGMEpw5A19R0vcwSfueI54fdmJiXh9wPv4PuoUkJve1NXOnd40/dsvrfqIqA/Xt78o3lP6xaPfxrj9R3PbleoVGlLydvB6mRCGbNN8uTIsrG522zwA7R7Qu4/uaMwI=
  - secure: EC/z78VIDnNhGWkcinTTwMkL6HSkn1WZHuoHLXfCDh6kHj1z2drIVSLs5ABItfC96YE6kiGJcucZegnYFWOIoSE9uEyxP3DsDD+e4VzVIank3CNUWSSJnHBFCtQgW1x8DISGYIuUg/TYY04pODoWXOokmECoT2e5GthLVD1MsypIbh6gZZVVdA0bhJEH6QDDgdmIhP2cwtzYvpQzjvhNo9UDozGKj2QbvhlkVELa0wv5MkgZtjZitws1PK9M5oMYhDULmOTnTaB0JlNDpnzU1cErbiPESuXmyfOkFFMHbS2l3Bmw+x6jl6NyZI6JssyxBYDjpr6QhGH3HgtW+E9YeNSHwADPKJ4AO0Chaw2cJv6fGgM5ZV2gzViCTNFigSiJYADfXwYgJFo6DlQKyBbkrqi6xx+Cq4FYh7b5uXMDOHXcCcl0oawAb77tw6krpoGOvD1quso+Qxc0jmhpDwuyi8LdMqoVJivxmxFoqU1comhNDba6F32nHK72iA4bHT847JBq0pWTKXfdUIMQOXV37seDrIj0OUg4jwLr1jbsyofMuaxJE1OQLiUg9YDUv08D/nPS2yH9k29z/JnorGEy4K0BABnToV/gNqf0+QSnTvDRKY3m+rBwCfV5G8U0rhGW2zlQP2BDh1GJ5se/8ouB0GJeLDhFgH0w9yJjVeZ4U0o=
  - secure: nEX3G4slPwkho1qkwqkuSmpRBYcQXEhADhaxBC6CwDBccckuxThpd/Q8a2NJmf5XrUNW836m+oDZU/2z+qqXgy0jRslHS9lNck5sR6Lf/P+H8EM73PuaCHLJCy2FlBFpAR23mqwO/IVWyNymiBdFGPhW0PH4+kNrSzXupFGqyepXmMn3pdFd1LjjlJkImtOUbtFKTgNhAGo9/UUu2FoYvFeLeeatmCNiXwFDX2FnZz+My06hRzPu5OCJQONUD1gBy43QmQRS4Un64ZtWLJK/8KuXPsfyN0kpf2HSQJSn6gi+fF/VvbrD/iLfrVM1+FfP9+NFgFnxVC+8BhuTM985j1aVuaD+ssSSc1FPoZZvcYh3LEy4yDMNV946p50Oxpw6JoNhdaj2K1zIk1MU0i5kkyqRo7AoMiJ9ePEdx1+qeWpgRENB/rqOZ80zcoU2jN01BiyjiLl65Nk0uW1KeaRllzgSqvETyMk8qTyJpNiaPxgUqUVRnvSVsEoECut/J77GTSWCaeIjang/ktXIhs15MV8vqAs/h7IBSPTtLyt7CXiIpbt69wgUsI0gOUrlOhi32PQIGEd20fl1BgKj0m9pXgphdEpeaENao94NOYifF+bZzbxkXZ2xvNLUYg9QjXaEIiPyPvwwstQVEQjRLvuV3SWxu5ItKud1ldUzn3zEQ54=
  - secure: V+ayKS4rK6orQ4ZVF2aotbnWd6T1fFxELzAR7XWX8OuQDdD4vyCk+pPYHmRvF5XbtU9FzKYKQ3eS7VZn2SGgzoMRGfq4H+BqRAINRMzUBjT0rUytIayWg0xupQINCoEVqVmK5fokIeiijJhPGhOjkVSHSdAFCpWBY5Egrrsv08bKOx+qEezTT8tR8XaJdzvDRMN472kywuVyailE3ehAwoqYMKTlmh0uK8UkFYTmtNUU4Z9cyfGdKnh2zLvWm9TI88iqtO0y8It0P0Aepdaf5UhEJ77XkWr221ieW9qglqKd9KvuJ+xYzozJOLZ62Zii3f0TWxY01r+FBTeoH5YF4QlogW7fjnH8g97uWTIunn/UKuYeEnmMnVY9ZRfyGbzHheQoHwn0xlCf6IfSR1ZRXbTh8wqoJ11reTBAlbTzggyLIZVpUseAw2hy4PGMuTY/QnI117uLfeVcBW4d5gcPG9Z7qYK66Xf76okP4/SFEvRFcHFc7cUFaKZybMWzzTtSh8rKIZXqmy2dyjkmdeUOUuqu65J8gp1kfIIVPWL2B5zFYkGNKRp1v1M4dB09EzfOQVLI5g79lzFYCLAZOzWmhrFwmeUkMOmbgp11d8tG0H+9kGX8cq4k6eHXn5GOKVsQa9qZXbzx32fTKWhtynIlECWQ++eOIaF7Rlyb8KS9bbU=
  - secure: bAU5lV8MXcGtFCLBPGghXBC211hyI/cZBP88/vXewpPTom0oqpyrr1MZ+nRyGjtIufwskQqRGKv9iAmZTNAcJ5H4UeYwkB4eDApkA7RBtmKDyxeVY7+Uhg6Vplg5pgbf7O3Gj2nwQ8eVC04J8S9POlZ+b7dxLkc1UJimd9m5KBBXwTJpzZtnpisjggKR8ybCPpY900rblDPEdlgCM2hgeli5uJxg32ngnRdlzY3DNvB40TalRVFue52worERCeiuVMWvv9759XopL7+KgXzc3yq/CqEfVNGksB32sI005Uajq3A8oD4aCJcRm5R+3Cbykv9fl5DyHVJUS5HlcjlHD/X0ovQdH5YZ20iZPbgXke/CWCYi4H/oJ2XQyuWkb/+jpIQdfoJN66lnT8sX3VPbLzNg7014LT1XcVN8v5ebWePwKChaQTdtb+mN5bvLOGkl83Ra5MkuuNOA+bxwpzakLy5GWsdiODuo4YPijzpQmySQwpuV1OE2DEzv8YYW+acmm063un/s1ns0QfJ2jZJNWmezeKp7pU8qtTBlAkF+4Yy6oKA2LSDadquEYuxv4DnRwX69PxdeqdQdmr3/Cp5vY10V1BTbmQcMs4yYnLJkgDlB3VvvHCO6I3OvucnmTIy9gnjTcByZ6YJLqbYQGYKRtt78ltSvDNFjiym8x573Gkk=
