language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ppsosqq@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.9 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=18.223.171.35
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: PMC7OF9yFtogEYcDfydkODMmrR68LzLoyfw8nfWzoiNNzzYocngRw69pGzJUTV6KSAdaut3ylmqVfSvBiPY6UQQNHFlGtEA7mvmXU+mgjICruvUZjUBhKNJgn3NErGRL8ROY2yyxSuvxt4F5r7xJHTHPHG9Yl7WU3RTRLKXoYoJdMKeEAbaiimg8MxEZVShQ1Tou3+JQYghTT1FVNbegyklVWDcBQ75mGN7mXfEIdZiERrufMXmMluGkklyEOqY1Fv7hHZ48SURf1k0eo8YYKfnp5qWXHUNFj8bhxF8ObO7EOgNiCcQ7BEvvfZYRczzsSyA1HGtVhDl4YHhP0cez39ebU3huW5oqE1gCPNL0QBUM9IPB2kgA6UWwD7QOa2bQCrkYWcqMeFP7CaWWYG4AeNjDaEDf0XYwHjFozEhPg0iwrIJB+0bD+8Sl7ub4Jr5f4MDp8eBpTmY5jXLQaZa/6ANJeQdyayi9zXyldhJV8Nb00oO1FvXeEB7drCUxq+elXBUuO6zs1ova61l2SztrueSoNIabp7YIVvOiAEkouGRcDcGMEpw5A19R0vcwSfueI54fdmJiXh9wPv4PuoUkJve1NXOnd40/dsvrfqIqA/Xt78o3lP6xaPfxrj9R3PbleoVGlLydvB6mRCGbNN8uTIsrG522zwA7R7Qu4/uaMwI=
  - secure: EC/z78VIDnNhGWkcinTTwMkL6HSkn1WZHuoHLXfCDh6kHj1z2drIVSLs5ABItfC96YE6kiGJcucZegnYFWOIoSE9uEyxP3DsDD+e4VzVIank3CNUWSSJnHBFCtQgW1x8DISGYIuUg/TYY04pODoWXOokmECoT2e5GthLVD1MsypIbh6gZZVVdA0bhJEH6QDDgdmIhP2cwtzYvpQzjvhNo9UDozGKj2QbvhlkVELa0wv5MkgZtjZitws1PK9M5oMYhDULmOTnTaB0JlNDpnzU1cErbiPESuXmyfOkFFMHbS2l3Bmw+x6jl6NyZI6JssyxBYDjpr6QhGH3HgtW+E9YeNSHwADPKJ4AO0Chaw2cJv6fGgM5ZV2gzViCTNFigSiJYADfXwYgJFo6DlQKyBbkrqi6xx+Cq4FYh7b5uXMDOHXcCcl0oawAb77tw6krpoGOvD1quso+Qxc0jmhpDwuyi8LdMqoVJivxmxFoqU1comhNDba6F32nHK72iA4bHT847JBq0pWTKXfdUIMQOXV37seDrIj0OUg4jwLr1jbsyofMuaxJE1OQLiUg9YDUv08D/nPS2yH9k29z/JnorGEy4K0BABnToV/gNqf0+QSnTvDRKY3m+rBwCfV5G8U0rhGW2zlQP2BDh1GJ5se/8ouB0GJeLDhFgH0w9yJjVeZ4U0o=
  - secure: bAU5lV8MXcGtFCLBPGghXBC211hyI/cZBP88/vXewpPTom0oqpyrr1MZ+nRyGjtIufwskQqRGKv9iAmZTNAcJ5H4UeYwkB4eDApkA7RBtmKDyxeVY7+Uhg6Vplg5pgbf7O3Gj2nwQ8eVC04J8S9POlZ+b7dxLkc1UJimd9m5KBBXwTJpzZtnpisjggKR8ybCPpY900rblDPEdlgCM2hgeli5uJxg32ngnRdlzY3DNvB40TalRVFue52worERCeiuVMWvv9759XopL7+KgXzc3yq/CqEfVNGksB32sI005Uajq3A8oD4aCJcRm5R+3Cbykv9fl5DyHVJUS5HlcjlHD/X0ovQdH5YZ20iZPbgXke/CWCYi4H/oJ2XQyuWkb/+jpIQdfoJN66lnT8sX3VPbLzNg7014LT1XcVN8v5ebWePwKChaQTdtb+mN5bvLOGkl83Ra5MkuuNOA+bxwpzakLy5GWsdiODuo4YPijzpQmySQwpuV1OE2DEzv8YYW+acmm063un/s1ns0QfJ2jZJNWmezeKp7pU8qtTBlAkF+4Yy6oKA2LSDadquEYuxv4DnRwX69PxdeqdQdmr3/Cp5vY10V1BTbmQcMs4yYnLJkgDlB3VvvHCO6I3OvucnmTIy9gnjTcByZ6YJLqbYQGYKRtt78ltSvDNFjiym8x573Gkk=
  - secure: SlxjA+zN9bmUMzufUi4mwldIjAT6JABG3nDRVw4y/8pDxcEzxSE3Cl6LmbUjqjS1Uf8mpTKsb+eRIY1r5N7kWXvNf2pM6i4n/PmwiwOlzFAqJm4YsTcXfMBqzjyj0xr9dKWWZSZ2JeMBQJudaZjSLqzrNSDr3iCaxFA0xigi/7RLtuyV3KYAcq+uVpdckcSB/+4DTZwj5U+2s9OhzRCx6NfrF08K3RiMvliZ4nMr1XPStUaJn0zkmRODrktUOVXFAPU7E0ShHhGbBWrFFPTK2SRmJLI07NnhtZm/z3y3bI++VN7KFiTE50IrFpin9NonpIZGg2f0Popk7YZhrCfwkm4cau4q7ecgipbcMR/F3yRm0i49e6lbhYVVgSrGrfCLus5L/JA5tMFkmRGGvT7W6kc/lDAcbx4Z/dFoEKcY/tUCKKAa+d98d7qfYnZerk3To98eW0aLxv1Tp8jtWrrkWNzHSYYl4nff/RU5tplcxX7nek32OAImaDf3oPzR0U9Yi9GDxbBEbztRlrN/nQlZ0oE7Zwz2Kbm5V4TMLjfbGRMEe6/9BTlzrjFWWFN7aAX9Iv2ncepphZuU/MFClvWSohPUDX/9MJfXb7fe+PhTI7aoojJ5dG01sm/mNiVfXHTdFDpp47sDZaVFIjC2XrsT49PJ2BpayYYwdCRIxmFU3J4=
  - secure: RAAqSrkuZVrnMBN2p8gCTiyJvy9hQSRvJLds2kwIpuBiXHJu9Aqf5jdJ19H21sx3TL1CO9am/vFgQQ1igZIFjEvjHSQsvnSmju6R2StEXwg3rGgVcDoN1iu9NQEhXxOkEq3rVLJNvVKw8v2JO2tRP2mXxbuoTptmSQahhlD8F+9ks/jcs0qdsuJxKg9IKZMTyKEYeqOic2NhvxOKZESWfYwDCKN0amTqv7IvenCpDofnYinkX+wniTHQPs/SjKyGMAH7/JPtCKBoggwZeKMgicLpuZUwNvAn4yETSaLGpgez5rfg+ubh+Xe1y5ICuCkz43QZT+WIUvjbk8MGzV8v/tI2U0FNev5iD6OvM47Bcmsp1pbXlzgotrdthLOiS9lJMjiL1okEKH5aGinzRRbmp+nMNVaIhyPTqR9/5pzcAylrRizkHuXNW+DXXKG3lj/3f/sjnGj7OvNNbcxCtdsgE//KivmY/+M670jrtuwkISejOgppQaqAz0j9SuD4S3hD5/BcEPzkCK/tIdlexmr4F+Et2r8z692YpLd9uUi4J7yci41k775iyOhWJ462nEqL0PPlm17rA4N8L7DyRElEMiHfJtZmvR2aiIRJ2LAIB2ni+dzfc6gHG2zNdJg0qmzaM1tZYIsBQvmpi7cxJ9t62H1Jr4fmpBKtmeVROBKtfZU=
